#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v13
# autospec commit: 2659038
#
# Source0 file verified with key 0x3A6A4DB839EAA6D7 (aacid@kde.org)
#
Name     : poppler-data-clr-rename
Version  : 0.4.12
Release  : 9
URL      : https://poppler.freedesktop.org/poppler-data-0.4.12.tar.gz
Source0  : https://poppler.freedesktop.org/poppler-data-0.4.12.tar.gz
Source1  : https://poppler.freedesktop.org/poppler-data-0.4.12.tar.gz.sig
Source2  : 3A6A4DB839EAA6D7.pkey
Summary  : Encoding files for use with poppler
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 MIT
Requires: poppler-data-clr-rename-data = %{version}-%{release}
Requires: poppler-data-clr-rename-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : gnupg
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
poppler-data
This package consists of encoding files for use with poppler.  The
encoding files are optional and poppler will automatically read them
if they are present.  When installed, the encoding files enables
poppler to correctly render CJK and Cyrillic properly.  While poppler
is licensed under the GPL, these encoding files have different license,
and thus distributed separately.

%package data
Summary: data components for the poppler-data-clr-rename package.
Group: Data

%description data
data components for the poppler-data-clr-rename package.


%package dev
Summary: dev components for the poppler-data-clr-rename package.
Group: Development
Requires: poppler-data-clr-rename-data = %{version}-%{release}
Provides: poppler-data-clr-rename-devel = %{version}-%{release}
Requires: poppler-data-clr-rename = %{version}-%{release}

%description dev
dev components for the poppler-data-clr-rename package.


%package license
Summary: license components for the poppler-data-clr-rename package.
Group: Default

%description license
license components for the poppler-data-clr-rename package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 3A6A4DB839EAA6D7' gpg.status
%setup -q -n poppler-data-0.4.12
cd %{_builddir}/poppler-data-0.4.12
pushd ..
cp -a poppler-data-0.4.12 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720113847
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720113847
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/poppler-data-clr-rename
cp %{_builddir}/poppler-data-%{version}/COPYING %{buildroot}/usr/share/package-licenses/poppler-data-clr-rename/86b5d7e4afc7594e53b1481438d09c6103891755 || :
cp %{_builddir}/poppler-data-%{version}/COPYING.adobe %{buildroot}/usr/share/package-licenses/poppler-data-clr-rename/4842b9aa2b376ba8ebd197bb21a5ba06c3bd43b0 || :
cp %{_builddir}/poppler-data-%{version}/COPYING.gpl2 %{buildroot}/usr/share/package-licenses/poppler-data-clr-rename/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-0
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-1
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-2
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-3
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-4
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-5
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-6
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-7
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-B5pc
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-ETen-B5
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-H-CID
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-H-Host
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-H-Mac
/usr/share/poppler/cMap/Adobe-CNS1/Adobe-CNS1-UCS2
/usr/share/poppler/cMap/Adobe-CNS1/B5-H
/usr/share/poppler/cMap/Adobe-CNS1/B5-V
/usr/share/poppler/cMap/Adobe-CNS1/B5pc-H
/usr/share/poppler/cMap/Adobe-CNS1/B5pc-UCS2
/usr/share/poppler/cMap/Adobe-CNS1/B5pc-UCS2C
/usr/share/poppler/cMap/Adobe-CNS1/B5pc-V
/usr/share/poppler/cMap/Adobe-CNS1/CNS-EUC-H
/usr/share/poppler/cMap/Adobe-CNS1/CNS-EUC-V
/usr/share/poppler/cMap/Adobe-CNS1/CNS1-H
/usr/share/poppler/cMap/Adobe-CNS1/CNS1-V
/usr/share/poppler/cMap/Adobe-CNS1/CNS2-H
/usr/share/poppler/cMap/Adobe-CNS1/CNS2-V
/usr/share/poppler/cMap/Adobe-CNS1/ETHK-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/ETHK-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/ETen-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/ETen-B5-UCS2
/usr/share/poppler/cMap/Adobe-CNS1/ETen-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/ETenms-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/ETenms-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/HKdla-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/HKdla-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/HKdlb-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/HKdlb-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/HKgccs-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/HKgccs-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/HKm314-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/HKm314-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/HKm471-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/HKm471-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/HKscs-B5-H
/usr/share/poppler/cMap/Adobe-CNS1/HKscs-B5-V
/usr/share/poppler/cMap/Adobe-CNS1/UCS2-B5pc
/usr/share/poppler/cMap/Adobe-CNS1/UCS2-ETen-B5
/usr/share/poppler/cMap/Adobe-CNS1/UniCNS-UCS2-H
/usr/share/poppler/cMap/Adobe-CNS1/UniCNS-UCS2-V
/usr/share/poppler/cMap/Adobe-CNS1/UniCNS-UTF16-H
/usr/share/poppler/cMap/Adobe-CNS1/UniCNS-UTF16-V
/usr/share/poppler/cMap/Adobe-CNS1/UniCNS-UTF32-H
/usr/share/poppler/cMap/Adobe-CNS1/UniCNS-UTF32-V
/usr/share/poppler/cMap/Adobe-CNS1/UniCNS-UTF8-H
/usr/share/poppler/cMap/Adobe-CNS1/UniCNS-UTF8-V
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-0
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-1
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-2
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-3
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-4
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-5
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-GBK-EUC
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-GBpc-EUC
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-H-CID
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-H-Host
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-H-Mac
/usr/share/poppler/cMap/Adobe-GB1/Adobe-GB1-UCS2
/usr/share/poppler/cMap/Adobe-GB1/GB-EUC-H
/usr/share/poppler/cMap/Adobe-GB1/GB-EUC-V
/usr/share/poppler/cMap/Adobe-GB1/GB-H
/usr/share/poppler/cMap/Adobe-GB1/GB-V
/usr/share/poppler/cMap/Adobe-GB1/GBK-EUC-H
/usr/share/poppler/cMap/Adobe-GB1/GBK-EUC-UCS2
/usr/share/poppler/cMap/Adobe-GB1/GBK-EUC-V
/usr/share/poppler/cMap/Adobe-GB1/GBK2K-H
/usr/share/poppler/cMap/Adobe-GB1/GBK2K-V
/usr/share/poppler/cMap/Adobe-GB1/GBKp-EUC-H
/usr/share/poppler/cMap/Adobe-GB1/GBKp-EUC-V
/usr/share/poppler/cMap/Adobe-GB1/GBT-EUC-H
/usr/share/poppler/cMap/Adobe-GB1/GBT-EUC-V
/usr/share/poppler/cMap/Adobe-GB1/GBT-H
/usr/share/poppler/cMap/Adobe-GB1/GBT-V
/usr/share/poppler/cMap/Adobe-GB1/GBTpc-EUC-H
/usr/share/poppler/cMap/Adobe-GB1/GBTpc-EUC-V
/usr/share/poppler/cMap/Adobe-GB1/GBpc-EUC-H
/usr/share/poppler/cMap/Adobe-GB1/GBpc-EUC-UCS2
/usr/share/poppler/cMap/Adobe-GB1/GBpc-EUC-UCS2C
/usr/share/poppler/cMap/Adobe-GB1/GBpc-EUC-V
/usr/share/poppler/cMap/Adobe-GB1/UCS2-GBK-EUC
/usr/share/poppler/cMap/Adobe-GB1/UCS2-GBpc-EUC
/usr/share/poppler/cMap/Adobe-GB1/UniGB-UCS2-H
/usr/share/poppler/cMap/Adobe-GB1/UniGB-UCS2-V
/usr/share/poppler/cMap/Adobe-GB1/UniGB-UTF16-H
/usr/share/poppler/cMap/Adobe-GB1/UniGB-UTF16-V
/usr/share/poppler/cMap/Adobe-GB1/UniGB-UTF32-H
/usr/share/poppler/cMap/Adobe-GB1/UniGB-UTF32-V
/usr/share/poppler/cMap/Adobe-GB1/UniGB-UTF8-H
/usr/share/poppler/cMap/Adobe-GB1/UniGB-UTF8-V
/usr/share/poppler/cMap/Adobe-Japan1/78-EUC-H
/usr/share/poppler/cMap/Adobe-Japan1/78-EUC-V
/usr/share/poppler/cMap/Adobe-Japan1/78-H
/usr/share/poppler/cMap/Adobe-Japan1/78-RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/78-RKSJ-V
/usr/share/poppler/cMap/Adobe-Japan1/78-V
/usr/share/poppler/cMap/Adobe-Japan1/78ms-RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/78ms-RKSJ-V
/usr/share/poppler/cMap/Adobe-Japan1/83pv-RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/90ms-RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/90ms-RKSJ-UCS2
/usr/share/poppler/cMap/Adobe-Japan1/90ms-RKSJ-V
/usr/share/poppler/cMap/Adobe-Japan1/90msp-RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/90msp-RKSJ-V
/usr/share/poppler/cMap/Adobe-Japan1/90pv-RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/90pv-RKSJ-UCS2
/usr/share/poppler/cMap/Adobe-Japan1/90pv-RKSJ-UCS2C
/usr/share/poppler/cMap/Adobe-Japan1/90pv-RKSJ-V
/usr/share/poppler/cMap/Adobe-Japan1/Add-H
/usr/share/poppler/cMap/Adobe-Japan1/Add-RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/Add-RKSJ-V
/usr/share/poppler/cMap/Adobe-Japan1/Add-V
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-0
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-1
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-2
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-3
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-4
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-5
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-6
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-7
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-90ms-RKSJ
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-90pv-RKSJ
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-H-CID
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-H-Host
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-H-Mac
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-PS-H
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-PS-V
/usr/share/poppler/cMap/Adobe-Japan1/Adobe-Japan1-UCS2
/usr/share/poppler/cMap/Adobe-Japan1/EUC-H
/usr/share/poppler/cMap/Adobe-Japan1/EUC-V
/usr/share/poppler/cMap/Adobe-Japan1/Ext-H
/usr/share/poppler/cMap/Adobe-Japan1/Ext-RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/Ext-RKSJ-V
/usr/share/poppler/cMap/Adobe-Japan1/Ext-V
/usr/share/poppler/cMap/Adobe-Japan1/H
/usr/share/poppler/cMap/Adobe-Japan1/Hankaku
/usr/share/poppler/cMap/Adobe-Japan1/Hiragana
/usr/share/poppler/cMap/Adobe-Japan1/Hojo-EUC-H
/usr/share/poppler/cMap/Adobe-Japan1/Hojo-EUC-V
/usr/share/poppler/cMap/Adobe-Japan1/Hojo-H
/usr/share/poppler/cMap/Adobe-Japan1/Hojo-V
/usr/share/poppler/cMap/Adobe-Japan1/Katakana
/usr/share/poppler/cMap/Adobe-Japan1/NWP-H
/usr/share/poppler/cMap/Adobe-Japan1/NWP-V
/usr/share/poppler/cMap/Adobe-Japan1/RKSJ-H
/usr/share/poppler/cMap/Adobe-Japan1/RKSJ-V
/usr/share/poppler/cMap/Adobe-Japan1/Roman
/usr/share/poppler/cMap/Adobe-Japan1/UCS2-90ms-RKSJ
/usr/share/poppler/cMap/Adobe-Japan1/UCS2-90pv-RKSJ
/usr/share/poppler/cMap/Adobe-Japan1/UniHojo-UCS2-H
/usr/share/poppler/cMap/Adobe-Japan1/UniHojo-UCS2-V
/usr/share/poppler/cMap/Adobe-Japan1/UniHojo-UTF16-H
/usr/share/poppler/cMap/Adobe-Japan1/UniHojo-UTF16-V
/usr/share/poppler/cMap/Adobe-Japan1/UniHojo-UTF32-H
/usr/share/poppler/cMap/Adobe-Japan1/UniHojo-UTF32-V
/usr/share/poppler/cMap/Adobe-Japan1/UniHojo-UTF8-H
/usr/share/poppler/cMap/Adobe-Japan1/UniHojo-UTF8-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UCS2-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UCS2-HW-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UCS2-HW-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UCS2-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UTF16-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UTF16-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UTF32-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UTF32-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UTF8-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS-UTF8-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS2004-UTF16-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS2004-UTF16-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS2004-UTF32-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS2004-UTF32-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS2004-UTF8-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJIS2004-UTF8-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJISPro-UCS2-HW-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJISPro-UCS2-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJISPro-UTF8-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJISX0213-UTF32-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJISX0213-UTF32-V
/usr/share/poppler/cMap/Adobe-Japan1/UniJISX02132004-UTF32-H
/usr/share/poppler/cMap/Adobe-Japan1/UniJISX02132004-UTF32-V
/usr/share/poppler/cMap/Adobe-Japan1/V
/usr/share/poppler/cMap/Adobe-Japan1/WP-Symbol
/usr/share/poppler/cMap/Adobe-Japan2/Adobe-Japan2-0
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-0
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-1
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-2
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-3
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-4
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-5
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-6
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-7
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-8
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-9
/usr/share/poppler/cMap/Adobe-KR/Adobe-KR-UCS2
/usr/share/poppler/cMap/Adobe-KR/UniAKR-UTF16-H
/usr/share/poppler/cMap/Adobe-KR/UniAKR-UTF32-H
/usr/share/poppler/cMap/Adobe-KR/UniAKR-UTF8-H
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-0
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-1
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-2
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-H-CID
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-H-Host
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-H-Mac
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-KSCms-UHC
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-KSCpc-EUC
/usr/share/poppler/cMap/Adobe-Korea1/Adobe-Korea1-UCS2
/usr/share/poppler/cMap/Adobe-Korea1/KSC-EUC-H
/usr/share/poppler/cMap/Adobe-Korea1/KSC-EUC-V
/usr/share/poppler/cMap/Adobe-Korea1/KSC-H
/usr/share/poppler/cMap/Adobe-Korea1/KSC-Johab-H
/usr/share/poppler/cMap/Adobe-Korea1/KSC-Johab-V
/usr/share/poppler/cMap/Adobe-Korea1/KSC-V
/usr/share/poppler/cMap/Adobe-Korea1/KSCms-UHC-H
/usr/share/poppler/cMap/Adobe-Korea1/KSCms-UHC-HW-H
/usr/share/poppler/cMap/Adobe-Korea1/KSCms-UHC-HW-V
/usr/share/poppler/cMap/Adobe-Korea1/KSCms-UHC-UCS2
/usr/share/poppler/cMap/Adobe-Korea1/KSCms-UHC-V
/usr/share/poppler/cMap/Adobe-Korea1/KSCpc-EUC-H
/usr/share/poppler/cMap/Adobe-Korea1/KSCpc-EUC-UCS2
/usr/share/poppler/cMap/Adobe-Korea1/KSCpc-EUC-UCS2C
/usr/share/poppler/cMap/Adobe-Korea1/KSCpc-EUC-V
/usr/share/poppler/cMap/Adobe-Korea1/UCS2-KSCms-UHC
/usr/share/poppler/cMap/Adobe-Korea1/UCS2-KSCpc-EUC
/usr/share/poppler/cMap/Adobe-Korea1/UniKS-UCS2-H
/usr/share/poppler/cMap/Adobe-Korea1/UniKS-UCS2-V
/usr/share/poppler/cMap/Adobe-Korea1/UniKS-UTF16-H
/usr/share/poppler/cMap/Adobe-Korea1/UniKS-UTF16-V
/usr/share/poppler/cMap/Adobe-Korea1/UniKS-UTF32-H
/usr/share/poppler/cMap/Adobe-Korea1/UniKS-UTF32-V
/usr/share/poppler/cMap/Adobe-Korea1/UniKS-UTF8-H
/usr/share/poppler/cMap/Adobe-Korea1/UniKS-UTF8-V
/usr/share/poppler/cidToUnicode/Adobe-CNS1
/usr/share/poppler/cidToUnicode/Adobe-GB1
/usr/share/poppler/cidToUnicode/Adobe-Japan1
/usr/share/poppler/cidToUnicode/Adobe-Korea1
/usr/share/poppler/nameToUnicode/Bulgarian
/usr/share/poppler/nameToUnicode/Greek
/usr/share/poppler/nameToUnicode/Thai
/usr/share/poppler/unicodeMap/Big5
/usr/share/poppler/unicodeMap/Big5ascii
/usr/share/poppler/unicodeMap/EUC-CN
/usr/share/poppler/unicodeMap/EUC-JP
/usr/share/poppler/unicodeMap/GBK
/usr/share/poppler/unicodeMap/ISO-2022-CN
/usr/share/poppler/unicodeMap/ISO-2022-JP
/usr/share/poppler/unicodeMap/ISO-2022-KR
/usr/share/poppler/unicodeMap/ISO-8859-6
/usr/share/poppler/unicodeMap/ISO-8859-7
/usr/share/poppler/unicodeMap/ISO-8859-8
/usr/share/poppler/unicodeMap/ISO-8859-9
/usr/share/poppler/unicodeMap/KOI8-R
/usr/share/poppler/unicodeMap/Latin2
/usr/share/poppler/unicodeMap/Shift-JIS
/usr/share/poppler/unicodeMap/TIS-620
/usr/share/poppler/unicodeMap/Windows-1255

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/poppler-data.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/poppler-data-clr-rename/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/poppler-data-clr-rename/4842b9aa2b376ba8ebd197bb21a5ba06c3bd43b0
/usr/share/package-licenses/poppler-data-clr-rename/86b5d7e4afc7594e53b1481438d09c6103891755
